apiVersion: v1
kind: Secret
metadata:
  name: artifactory-registry-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" .  }}

