apiVersion: v1
kind: Secret
metadata:
  {{- range .Values.ingress.tls }}
  name: {{ .secretName }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsSecrets.crt | b64enc }}
  tls.key: {{ .Values.tlsSecrets.key | b64enc }}
