---
apiVersion: v1
kind: Service
metadata:
    name: {{ template "apache-nifi.fullname" . }}-headless
    labels:
        app: {{ include "apache-nifi.name" . | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
    type: {{ .Values.service.headless.type }}
    clusterIP: None
    ports:
{{- if .Values.properties.clusterSecure }}
    - port: {{ .Values.properties.httpsPort }}
      name: https
{{- else}}
    - port: {{ .Values.properties.httpPort }}
      name: http
{{- end }}
    - port: {{ .Values.properties.clusterPort }}
      name: cluster
    - port: {{ .Values.properties.cachePort }}
      name: cache
    - port: {{ .Values.properties.jobPort }}
      name: job
    selector:
        app: {{ include "apache-nifi.name" . | quote }}
        release: {{ .Release.Name | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache-nifi.fullname" . }}
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.clusterip.type }}
  ports:
    - port: {{ .Values.service.clusterip.port}}
      name: https
      targetPort: {{ .Values.properties.httpsPort }}
  selector:
    app: {{ template "apache-nifi.name" . }}
    release: {{ .Release.Name }}
